"""Unit coverage for the one-way baseline importer.

The optional live-PostgreSQL test deliberately requires a *dedicated empty
database* URL.  It never falls back to DATABASE_URL, so it cannot accidentally
write to the production funnel_tracking database.
"""

from __future__ import annotations

import os
import sqlite3
from pathlib import Path

import pytest

from db_migrations.sqlite_to_postgres import (
    dependency_order,
    expected_counts,
    json_columns,
    normalized_row,
    postgres_row,
    pg_ddl,
    pg_index_ddl,
    pg_url,
    sqlite_snapshot,
    table_columns,
)


def test_table_translation_preserves_legacy_wall_time_and_constraints() -> None:
    translated = pg_ddl(
        """CREATE TABLE example (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          active BOOLEAN DEFAULT 1,
          payload_json TEXT NOT NULL DEFAULT '{}',
          score REAL,
          CHECK (active IN (0, 1))
        )"""
    )
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated
    assert "created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP" in translated
    assert "active BOOLEAN DEFAULT TRUE" in translated
    assert "payload_json JSONB NOT NULL DEFAULT '{}'" in translated
    assert "score DOUBLE PRECISION" in translated
    assert "CHECK (active IN (FALSE, TRUE))" in translated


def test_expression_index_translation_uses_jsonb_operator_and_partial_predicate() -> None:
    translated = pg_index_ddl(
        """CREATE UNIQUE INDEX idx_active
        ON action_queue(target_id, COALESCE(json_extract(payload_json, '$.dedupe_key'), ''))
        WHERE status NOT IN ('executed', 'failed')"""
    )
    assert translated.startswith("CREATE UNIQUE INDEX IF NOT EXISTS idx_active")
    assert "(payload_json ->> 'dedupe_key')" in translated
    assert "WHERE status NOT IN ('executed', 'failed')" in translated


def test_boolean_index_predicate_uses_postgres_boolean_literal() -> None:
    assert "WHERE dry_run = FALSE" in pg_index_ddl(
        "CREATE INDEX reactions_live ON reactions(item_id) WHERE dry_run = 0", {"dry_run"}
    )


def test_normalization_rejects_invalid_json_and_boolean() -> None:
    assert normalized_row(
        ('{"key": 1}', "1"), ["payload_json", "dry_run"], {"payload_json"}, {"dry_run"}, "example"
    ) == ({"key": 1}, True)
    with pytest.raises(ValueError, match="Invalid JSON"):
        normalized_row(("not-json",), ["payload_json"], {"payload_json"}, set(), "example")
    with pytest.raises(ValueError, match="Invalid SQLite boolean"):
        normalized_row((2,), ["dry_run"], set(), {"dry_run"}, "example")


def test_postgres_row_explicitly_adapts_parsed_json_for_jsonb() -> None:
    class JsonbMarker:
        def __init__(self, value):
            self.value = value

    adapted = postgres_row(
        ('{"key": 1}', 1),
        ["payload_json", "dry_run"],
        {"payload_json"},
        {"dry_run"},
        "example",
        json_adapter=JsonbMarker,
    )
    assert isinstance(adapted[0], JsonbMarker)
    assert adapted[0].value == {"key": 1}
    assert adapted[1] is True


def test_snapshot_is_consistent_and_dependency_order_is_parent_first(tmp_path: Path) -> None:
    source = tmp_path / "source.db"
    conn = sqlite3.connect(source)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.executescript(
        """
        CREATE TABLE parent (id INTEGER PRIMARY KEY AUTOINCREMENT, payload_json TEXT, active BOOLEAN);
        CREATE TABLE child (id INTEGER PRIMARY KEY AUTOINCREMENT, parent_id INTEGER REFERENCES parent(id));
        INSERT INTO parent(payload_json, active) VALUES ('{"ok":true}', 1);
        INSERT INTO child(parent_id) VALUES (1);
        """
    )
    conn.commit()
    conn.close()

    snapshot, temporary = sqlite_snapshot(source)
    try:
        tables = [row[0] for row in snapshot.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")]
        assert dependency_order(snapshot, tables) == ["parent", "child"]
        assert expected_counts(snapshot, tables) == {"parent": 1, "child": 1}
        assert json_columns(snapshot, "parent") == {"payload_json"}
        assert table_columns(snapshot, "parent") == ["id", "payload_json", "active"]
    finally:
        snapshot.close()
        temporary.cleanup()


def test_dependency_order_handles_catalog_name_sort_that_postgres_cannot() -> None:
    """SQLite catalog order can put event_campaigns before events alphabetically."""
    conn = sqlite3.connect(":memory:")
    conn.executescript(
        """
        CREATE TABLE events (id INTEGER PRIMARY KEY AUTOINCREMENT);
        CREATE TABLE event_campaigns (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER REFERENCES events(id));
        """
    )
    catalog_order = [
        row[0]
        for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    ]
    assert catalog_order == ["event_campaigns", "events"]
    assert dependency_order(conn, catalog_order) == ["events", "event_campaigns"]


def test_postgres_url_rejects_sqlite_and_accepts_sqlalchemy_spelling() -> None:
    assert pg_url("postgresql+psycopg://user:pass@db/name") == "postgresql://user:pass@db/name"
    with pytest.raises(ValueError, match="never sqlite"):
        pg_url("sqlite:///source.db")


@pytest.mark.skipif(not os.getenv("POSTGRES_MIGRATION_TEST_URL"), reason="requires dedicated empty PostgreSQL test database")
def test_live_postgres_import_requires_explicit_dedicated_database(tmp_path: Path) -> None:
    """Opt-in smoke test for CI; URL must point to an ephemeral database only."""
    import psycopg

    from db_migrations.sqlite_to_postgres import import_snapshot, verify_counts

    url = pg_url(os.environ["POSTGRES_MIGRATION_TEST_URL"])
    assert "funnel_tracking" not in url.rsplit("/", 1)[-1], "Never point this test at the production database"
    source = tmp_path / "source.db"
    sqlite = sqlite3.connect(source)
    sqlite.executescript(
        """
        CREATE TABLE item (id INTEGER PRIMARY KEY AUTOINCREMENT, happened_at DATETIME, payload_json TEXT, enabled BOOLEAN DEFAULT 1);
        CREATE INDEX item_payload_key ON item(json_extract(payload_json, '$.key'));
        INSERT INTO item(happened_at, payload_json, enabled) VALUES ('2026-09-19 13:00:00', '{"key":"a"}', 1);
        """
    )
    sqlite.commit()
    sqlite.close()
    snapshot, temporary = sqlite_snapshot(source)
    try:
        import_snapshot(snapshot, url, create_schema=True, allow_nonempty=False)
        assert verify_counts(snapshot, url) == {"item": (1, 1)}
        with psycopg.connect(url) as pg, pg.cursor() as cur:
            cur.execute("SELECT happened_at::text, payload_json->>'key', enabled FROM item")
            assert cur.fetchone() == ("2026-09-19 13:00:00", "a", True)
    finally:
        snapshot.close()
        temporary.cleanup()
