#!/usr/bin/env python3
"""Create a PostgreSQL baseline from a Funnel Tracking SQLite snapshot.

This tool is deliberately not an application adapter.  Run it once during a
controlled cutover after stopping all SQLite writers.  It never mutates the
SQLite file: a SQLite online backup is used as the import source.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable


APP_TABLE_SQL = """
SELECT name, sql FROM sqlite_master
WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
ORDER BY name
"""
APP_INDEX_SQL = """
SELECT name, sql FROM sqlite_master
WHERE type = 'index' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
ORDER BY name
"""
IDENTITY_PK = re.compile(r"\bid\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I)
JSON_COLUMN = re.compile(r"\b([a-zA-Z_][a-zA-Z0-9_]*_json)\s+TEXT\b", re.I)
BOOLEAN_DECLARATION = re.compile(r"\b([a-zA-Z_][a-zA-Z0-9_]*)\s+BOOLEAN\b", re.I)
INDEX_TABLE = re.compile(r"\bON\s+(?:\"([^\"]+)\"|([a-zA-Z_][a-zA-Z0-9_]*))", re.I)


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_url(value: str) -> str:
    """Accept the documented URL spelling but reject accidental SQLite URLs."""
    if value.startswith("postgresql+psycopg://"):
        return "postgresql://" + value[len("postgresql+psycopg://") :]
    if not value.startswith(("postgresql://", "postgres://")):
        raise ValueError("DATABASE_URL must start with postgresql:// (never sqlite://)")
    return value


def pg_ddl(sql: str) -> str:
    """Translate only catalog forms used by the checked-in Funnel SQLite DB."""
    boolean_cols = {match.group(1) for match in BOOLEAN_DECLARATION.finditer(sql)}
    result = re.sub(r"^CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", sql.strip(), flags=re.I)
    result = IDENTITY_PK.sub("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", result)
    result = re.sub(r"\bAUTOINCREMENT\b", "", result, flags=re.I)
    result = re.sub(r"\bDATETIME\b", "TIMESTAMP WITHOUT TIME ZONE", result, flags=re.I)
    result = re.sub(r"\bBOOLEAN\s+DEFAULT\s+1\b", "BOOLEAN DEFAULT TRUE", result, flags=re.I)
    result = re.sub(r"\bBOOLEAN\s+DEFAULT\s+0\b", "BOOLEAN DEFAULT FALSE", result, flags=re.I)
    # SQLite uses 0/1 for booleans even in CHECK constraints. PostgreSQL has no
    # boolean=integer operator, so translate only columns declared BOOLEAN in
    # this same table definition.
    for column in boolean_cols:
        escaped = re.escape(column)
        result = re.sub(rf"\b{escaped}\s*=\s*0\b", f"{column} = FALSE", result, flags=re.I)
        result = re.sub(rf"\b{escaped}\s*=\s*1\b", f"{column} = TRUE", result, flags=re.I)
        result = re.sub(rf"\b{escaped}\s+IN\s*\(\s*0\s*,\s*1\s*\)", f"{column} IN (FALSE, TRUE)", result, flags=re.I)
    result = JSON_COLUMN.sub(lambda m: f'{m.group(1)} JSONB', result)
    result = re.sub(r"\bINTEGER\b", "BIGINT", result, flags=re.I)
    result = re.sub(r"\bREAL\b", "DOUBLE PRECISION", result, flags=re.I)
    return result + ";"


def pg_index_ddl(sql: str, boolean_cols: set[str] | None = None) -> str:
    result = re.sub(r"^CREATE (UNIQUE )?INDEX ", lambda m: f"CREATE {m.group(1) or ''}INDEX IF NOT EXISTS ", sql.strip(), flags=re.I)
    # Only current expression indexes use SQLite's json_extract(). JSON columns
    # are imported as jsonb, so PostgreSQL can index the same logical key.
    result = re.sub(
        r"json_extract\((\w+),\s*'\$\.(\w+)'\)",
        lambda m: f"({m.group(1)} ->> '{m.group(2)}')",
        result,
        flags=re.I,
    )
    for column in boolean_cols or set():
        escaped = re.escape(column)
        result = re.sub(rf"\b{escaped}\s*=\s*0\b", f"{column} = FALSE", result, flags=re.I)
        result = re.sub(rf"\b{escaped}\s*=\s*1\b", f"{column} = TRUE", result, flags=re.I)
    return result + ";"


def index_table(sql: str) -> str | None:
    """Return the unquoted table name used by a current SQLite CREATE INDEX."""
    match = INDEX_TABLE.search(sql)
    return (match.group(1) or match.group(2)) if match else None


def sqlite_snapshot(source: Path) -> tuple[sqlite3.Connection, tempfile.TemporaryDirectory[str]]:
    """Return a read-only consistent backup; handles a source in WAL mode."""
    if not source.is_file():
        raise FileNotFoundError(source)
    tmp = tempfile.TemporaryDirectory(prefix="funnel-sqlite-snapshot-")
    copy_path = Path(tmp.name) / source.name
    src = sqlite3.connect(f"file:{source.absolute()}?mode=ro", uri=True)
    dst = sqlite3.connect(copy_path)
    try:
        src.backup(dst)
    finally:
        dst.close()
        src.close()
    return sqlite3.connect(copy_path), tmp


def table_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [str(row[1]) for row in conn.execute(f"PRAGMA table_info({quote_ident(table)})")]


def json_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    return {column for column in table_columns(conn, table) if column.endswith("_json")}


def boolean_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    return {
        str(row[1])
        for row in conn.execute(f"PRAGMA table_info({quote_ident(table)})")
        if str(row[2]).upper() == "BOOLEAN"
    }


def dump_rows(conn: sqlite3.Connection, table: str) -> Iterable[tuple[Any, ...]]:
    columns = table_columns(conn, table)
    select = ", ".join(quote_ident(column) for column in columns)
    yield from conn.execute(f"SELECT {select} FROM {quote_ident(table)}")


def normalized_row(
    row: tuple[Any, ...], columns: list[str], json_cols: set[str], bool_cols: set[str], table: str
) -> tuple[Any, ...]:
    values = list(row)
    for index, column in enumerate(columns):
        if column not in json_cols or values[index] is None:
            continue
        try:
            values[index] = json.loads(values[index])
        except (TypeError, json.JSONDecodeError) as exc:
            raise ValueError(f"Invalid JSON in {table}.{column}: {exc}") from exc
    for index, column in enumerate(columns):
        if column in bool_cols and values[index] is not None:
            if values[index] not in (0, 1, False, True, "0", "1"):
                raise ValueError(f"Invalid SQLite boolean in {table}.{column}: {values[index]!r}")
            values[index] = values[index] in (1, True, "1")
    return tuple(values)


def postgres_row(
    row: tuple[Any, ...],
    columns: list[str],
    json_cols: set[str],
    bool_cols: set[str],
    table: str,
    *,
    json_adapter: Any,
) -> tuple[Any, ...]:
    """Normalize SQLite values then mark parsed JSON for psycopg JSONB adaption.

    psycopg intentionally does not guess that a Python ``dict`` belongs in a
    JSON/JSONB SQL parameter.  Explicitly using ``Jsonb`` avoids the
    ``cannot adapt type 'dict'`` failure while retaining the importer's early
    JSON validation.
    """
    values = list(normalized_row(row, columns, json_cols, bool_cols, table))
    for index, column in enumerate(columns):
        if column in json_cols and values[index] is not None:
            values[index] = json_adapter(values[index])
    return tuple(values)


def expected_counts(conn: sqlite3.Connection, tables: list[str]) -> dict[str, int]:
    return {table: int(conn.execute(f"SELECT COUNT(*) FROM {quote_ident(table)}").fetchone()[0]) for table in tables}


def dependency_order(conn: sqlite3.Connection, tables: list[str]) -> list[str]:
    """Parents precede children so immediate PostgreSQL foreign keys import."""
    pending = set(tables)
    dependencies = {
        table: {str(row[2]) for row in conn.execute(f"PRAGMA foreign_key_list({quote_ident(table)})") if str(row[2]) in pending}
        for table in tables
    }
    ordered: list[str] = []
    while pending:
        ready = sorted(table for table in pending if not (dependencies[table] & pending))
        if not ready:
            raise RuntimeError(f"SQLite foreign-key cycle cannot be imported safely: {sorted(pending)}")
        ordered.extend(ready)
        pending.difference_update(ready)
    return ordered


def require_empty_target(pg_conn: Any, allow_nonempty: bool) -> None:
    with pg_conn.cursor() as cur:
        cur.execute("""
            SELECT count(*) FROM information_schema.tables
            WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
        """)
        existing = int(cur.fetchone()[0])
    if existing and not allow_nonempty:
        raise RuntimeError(
            f"Target public schema already has {existing} table(s). Refusing to mix imports; use an empty database."
        )


def import_snapshot(snapshot: sqlite3.Connection, database_url: str, create_schema: bool, allow_nonempty: bool) -> None:
    try:
        import psycopg  # type: ignore[import-not-found]
        from psycopg.types.json import Jsonb  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError("Missing dependency. Run: pip install -e '.[postgres]'") from exc

    tables_and_sql = list(snapshot.execute(APP_TABLE_SQL))
    tables = dependency_order(snapshot, [str(row[0]) for row in tables_and_sql])
    table_sql_by_name = {str(name): str(sql) for name, sql in tables_and_sql}
    indexes = list(snapshot.execute(APP_INDEX_SQL))
    with psycopg.connect(database_url) as pg_conn:
        require_empty_target(pg_conn, allow_nonempty)
        with pg_conn.cursor() as cur:
            if create_schema:
                # SQLite permits creating a child before its referenced parent;
                # PostgreSQL does not.  Reuse the FK topological ordering needed
                # for the copy rather than relying on sqlite_master's name sort.
                for table in tables:
                    cur.execute(pg_ddl(table_sql_by_name[table]))
                for _name, sql in indexes:
                    table = index_table(str(sql))
                    cur.execute(pg_index_ddl(str(sql), boolean_columns(snapshot, table) if table else set()))
            identity_tables = {str(name) for name, sql in tables_and_sql if IDENTITY_PK.search(str(sql))}
            for table in tables:
                columns = table_columns(snapshot, table)
                if not columns:
                    continue
                insert = f"INSERT INTO {quote_ident(table)} ({', '.join(map(quote_ident, columns))}) VALUES ({', '.join(['%s'] * len(columns))})"
                rows = (
                    postgres_row(
                        row,
                        columns,
                        json_columns(snapshot, table),
                        boolean_columns(snapshot, table),
                        table,
                        json_adapter=Jsonb,
                    )
                    for row in dump_rows(snapshot, table)
                )
                cur.executemany(insert, rows)
                if table in identity_tables:
                    cur.execute(
                        "SELECT setval(pg_get_serial_sequence(%s, 'id'), COALESCE((SELECT MAX(id) FROM "
                        + quote_ident(table)
                        + "), 1), (SELECT COUNT(*) > 0 FROM "
                        + quote_ident(table)
                        + "))",
                        (table,),
                    )
        pg_conn.commit()


def verify_counts(snapshot: sqlite3.Connection, database_url: str) -> dict[str, tuple[int, int]]:
    try:
        import psycopg  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError("Missing dependency. Run: pip install -e '.[postgres]'") from exc
    tables = [str(row[0]) for row in snapshot.execute(APP_TABLE_SQL)]
    source = expected_counts(snapshot, tables)
    with psycopg.connect(database_url) as pg_conn, pg_conn.cursor() as cur:
        target = {}
        for table in tables:
            cur.execute(f"SELECT COUNT(*) FROM {quote_ident(table)}")
            target[table] = int(cur.fetchone()[0])
    return {table: (source[table], target[table]) for table in tables}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sqlite", required=True, type=Path, help="SQLite source; never modified")
    parser.add_argument("--database-url", default=os.getenv("DATABASE_URL"), help="PostgreSQL URL (or DATABASE_URL)")
    parser.add_argument("--create-schema", action="store_true", help="Create translated tables and indexes")
    parser.add_argument("--verify", action="store_true", help="Compare source and target row counts")
    parser.add_argument("--allow-nonempty", action="store_true", help="Override empty-target protection (not for normal retries)")
    parser.add_argument("--dry-run", action="store_true", help="Read SQLite catalog only; do not connect to PostgreSQL")
    args = parser.parse_args()
    if not args.dry_run and not args.database_url:
        parser.error("--database-url or DATABASE_URL is required unless --dry-run is used")
    if not args.dry_run and not (args.create_schema or args.verify):
        parser.error("choose --create-schema for an import and/or --verify for a read-only comparison")

    snapshot, tempdir = sqlite_snapshot(args.sqlite)
    try:
        tables = [str(row[0]) for row in snapshot.execute(APP_TABLE_SQL)]
        counts = expected_counts(snapshot, tables)
        print(f"SQLite snapshot: {args.sqlite} ({len(tables)} application tables, {sum(counts.values())} rows)")
        if args.dry_run:
            for table in tables:
                print(f"{table}: {counts[table]}")
            return 0
        database_url = pg_url(args.database_url)
        if args.create_schema:
            import_snapshot(snapshot, database_url, create_schema=True, allow_nonempty=args.allow_nonempty)
        if args.verify:
            mismatches = {name: counts for name, counts in verify_counts(snapshot, database_url).items() if counts[0] != counts[1]}
            if mismatches:
                for name, (source, target) in mismatches.items():
                    print(f"MISMATCH {name}: sqlite={source} postgresql={target}", file=sys.stderr)
                return 2
            print(f"Verified {len(tables)} tables: PostgreSQL row counts match SQLite.")
        return 0
    finally:
        snapshot.close()
        tempdir.cleanup()


if __name__ == "__main__":
    raise SystemExit(main())
